on block break:
    player is sneaking
    veinminer(event-location, player)

function veinminer(l: location, p: player):
    damage {_p}'s tool by 1
    set {_drops::*} to drops of block at {_l} using {_p}'s tool
    drop {_drops::*} at {_l}
    set block at {_l} to air
    loop blocks in radius 1 of {_l}:
        if loop-block is any ore:
            veinminer(location of loop-block, {_p}'s tool)
